<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SHOP</name>
   <tag></tag>
   <elementGuidId>0211c9e9-e526-4f46-b93f-e797138d9841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-header[@id='header']/app-toolbar/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header > app-toolbar > div.logo > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>275931ed-79f6-469d-ac49-f50978972e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>849f46ae-213a-41e3-86d9-0551d639e25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SHOP Home</value>
      <webElementGuid>e39fb513-ab47-4634-8e59-d94f25586572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHOP</value>
      <webElementGuid>96e5aa0f-9ec5-4365-b80b-1d170275aa61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/app-header[@id=&quot;header&quot;]/app-toolbar[1]/div[@class=&quot;logo&quot;]/a[1]</value>
      <webElementGuid>7b139195-bf16-4f31-9521-e76c1a3bb9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Mens Outerwear - SHOP/shop-app_SHOP</value>
      <webElementGuid>1f88abc0-c637-4ac7-8edc-c75a70fc9dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9a883532-4525-4f2a-8c5c-a7e4f92549cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-header[@id='header']/app-toolbar/div[2]/a</value>
      <webElementGuid>729905b6-37fb-4f2d-ab6b-8b89e9974f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SHOP')]</value>
      <webElementGuid>3f851a7f-e444-4498-8771-d335a8126ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHOP']/parent::*</value>
      <webElementGuid>87ba6baf-e1f9-4e26-8f0a-7bf33e01f879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/')]</value>
      <webElementGuid>cf7f0033-6e3e-41d0-b4dc-5128c985d37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'SHOP' or . = 'SHOP')]</value>
      <webElementGuid>c4116005-66ef-4c33-9f15-db045286dced</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
