<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shop-list_list</name>
   <tag></tag>
   <elementGuidId>a5ca653c-264f-4285-b87b-a15d09b9859c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//shop-list[@name = 'list']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iron-pages > shop-list[name=&quot;list&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shop-list</value>
      <webElementGuid>0dd340ee-89e8-460c-8fda-cf6c0b31afdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>65b02a21-0517-411d-880e-d49bf2c9979c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iron-selected</value>
      <webElementGuid>a406737d-b988-44a8-baab-45a49f34bf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/iron-pages[1]/shop-list[@class=&quot;iron-selected&quot;]</value>
      <webElementGuid>2a7038a3-4378-49f4-9ea2-e53869169b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Mens Outerwear - SHOP/shop-app_SHOP</value>
      <webElementGuid>b10aa622-e64d-4bb6-8ef3-15628397fc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>79f31709-1495-4bb2-9d10-8db34c6ce244</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//shop-list[@name = 'list']</value>
      <webElementGuid>9134c969-e144-4ec0-b632-f6b583326bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
