<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shop-app_SHOP</name>
   <tag></tag>
   <elementGuidId>5b063b3b-040b-443f-aa8c-93007b1c6c3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>shop-app</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/img[@id=', '&quot;', 'img', '&quot;', ']')])[1]/preceding::shop-app[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shop-app</value>
      <webElementGuid>ff7abbd1-dfe8-4f7e-8587-f5c0f44d420f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>page</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>a1096ba2-4cb9-45b4-af7f-ef7d471ca93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHOP</value>
      <webElementGuid>7d72aa4c-a33e-42cb-aca5-07358452ad49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/shop-app[1]</value>
      <webElementGuid>fba0394f-031f-450f-b774-13752a44d2dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/img[@id=', '&quot;', 'img', '&quot;', ']')])[1]/preceding::shop-app[1]</value>
      <webElementGuid>7b6f9068-abf1-48b2-b414-a0bbbb99329f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHOP']/parent::*</value>
      <webElementGuid>2c832d56-3b7f-4b64-9c90-d60a43ea1260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//shop-app</value>
      <webElementGuid>131dd9d9-40d4-4732-9640-c81e792d015e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//shop-app[(text() = 'SHOP' or . = 'SHOP')]</value>
      <webElementGuid>a7d7e1b7-f352-4cc0-9d32-70c62bf9c1ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
