<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>book-app_BOOKS</name>
   <tag></tag>
   <elementGuidId>7f097f25-0207-42c0-b367-a3a6c07d0e79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='BOOKS']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>book-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>book-app</value>
      <webElementGuid>ac626941-0efd-40af-b5c8-79d49ab91eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>apptitle</name>
      <type>Main</type>
      <value>BOOKS</value>
      <webElementGuid>c65b15bc-4f5f-4a15-ab9b-8f68696b3984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOOKS</value>
      <webElementGuid>13f5aaca-df03-4206-9672-820705649bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/book-app[1]</value>
      <webElementGuid>90ee6677-cde9-47b2-8ef7-297a052b422d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BOOKS']/parent::*</value>
      <webElementGuid>4de12dbf-da91-4463-bad2-946142d5e77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//book-app</value>
      <webElementGuid>e9beba84-e819-4bae-93d6-2b41b7e68fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//book-app[(text() = 'BOOKS' or . = 'BOOKS')]</value>
      <webElementGuid>b5c33b7f-6a34-4269-a13c-94e63a569c61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
