<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>book-explore__page</name>
   <tag></tag>
   <elementGuidId>366934c2-a779-4eb4-8f49-5eb55224eee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>main.main-content > book-explore._page</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>book-explore</value>
      <webElementGuid>9302e2da-6cba-4e7f-a984-66c58fad63af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_page</value>
      <webElementGuid>adb1a79f-5f14-4af2-8c4b-81f51b22d20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/main[@class=&quot;main-content&quot;]/book-explore[@class=&quot;_page&quot;]</value>
      <webElementGuid>bcbc0a8d-096b-41e5-8e27-de26c79f0951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Books/Page_automation - Books/book-app_BOOKS</value>
      <webElementGuid>e5c83b59-203f-4862-9e7f-d0b1c2d8e4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0404cff-0437-489e-ac5c-7814b82f47a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
