<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shop-app_SHOP</name>
   <tag></tag>
   <elementGuidId>c5866d12-32ce-4ba3-9551-0479786fc759</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='SHOP']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>shop-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shop-app</value>
      <webElementGuid>61960bd8-516a-46f7-8a73-b9787414a884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>page</name>
      <type>Main</type>
      <value>cart</value>
      <webElementGuid>f4a1c9c6-ff92-418a-9c4f-094cb4195462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHOP</value>
      <webElementGuid>ec8a401b-4048-4aa3-873e-0af3d99547dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/shop-app[1]</value>
      <webElementGuid>fd857bb4-d711-4048-b46e-653a9128a1d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHOP']/parent::*</value>
      <webElementGuid>7fddce60-65dd-48af-bcfc-12fda06432c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//shop-app</value>
      <webElementGuid>4e46816f-f5ca-4e20-8a56-e199ca231845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//shop-app[(text() = 'SHOP' or . = 'SHOP')]</value>
      <webElementGuid>12619275-3a65-4747-934f-a36af181a2eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
