<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BOOKS</name>
   <tag></tag>
   <elementGuidId>f3b73593-67a7-4ba7-8ba0-f522fe600390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'BOOKS')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-header > app-toolbar.toolbar-top > div > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c471ac0d-75da-4680-aecf-1ea1fd6f0079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>a7ac9e2d-8bab-4133-8a8e-411a408569a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOOKS</value>
      <webElementGuid>de508aa8-48b1-4f69-952d-39cd8baf6a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/app-header[1]/app-toolbar[@class=&quot;toolbar-top&quot;]/div[1]/a[1]</value>
      <webElementGuid>fb90d9db-49e9-4c66-98bc-c3b5df06f306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Books/Page_Books/book-app_BOOKS</value>
      <webElementGuid>dd1d3f60-ea09-439c-8237-228283c6414d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b62cc674-cc4a-49c7-9575-80943e990d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BOOKS')]</value>
      <webElementGuid>cbb4ac1f-0899-4bba-b643-d73c2b91554f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BOOKS']/parent::*</value>
      <webElementGuid>5eab7c8a-e974-4b26-89e7-a17d7cd0071b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/')]</value>
      <webElementGuid>a25ff6fc-207f-4635-9fd2-03408c0402f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'BOOKS' or . = 'BOOKS')]</value>
      <webElementGuid>d7c56921-468c-43fd-bc97-8aa1bfb86def</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
