<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>book-app_BOOKS</name>
   <tag></tag>
   <elementGuidId>ad9f423a-2ee8-428d-885b-3a4a9f5c533b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='/button[1]'])[1]/preceding::book-app[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>book-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>book-app</value>
      <webElementGuid>62f372c1-4174-493b-bc11-beeaba87872f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>apptitle</name>
      <type>Main</type>
      <value>BOOKS</value>
      <webElementGuid>b5d63edb-7586-4f12-8bb0-114d0e78789e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOOKS</value>
      <webElementGuid>fbc073bd-9eca-4c77-9117-f624a5f1938e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/book-app[1]</value>
      <webElementGuid>a865a114-16e4-4359-8669-b4c766cbf630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/button[1]'])[1]/preceding::book-app[1]</value>
      <webElementGuid>659b6957-7d0f-4355-9391-33b349777b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BOOKS']/parent::*</value>
      <webElementGuid>b749bce2-bc72-493f-8a5e-ccebd6c814c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//book-app</value>
      <webElementGuid>fd5595e0-de52-440c-ad20-3900c26dff52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//book-app[(text() = 'BOOKS' or . = 'BOOKS')]</value>
      <webElementGuid>6b48a383-bffd-4646-8968-677c86411343</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
