<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>book-app_BOOKS</name>
   <tag></tag>
   <elementGuidId>2b8f89ec-7947-462a-8f48-382d63e5278a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='BOOKS']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>book-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>book-app</value>
      <webElementGuid>e8079e0b-8163-4c85-bfbe-de3731cf36f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>apptitle</name>
      <type>Main</type>
      <value>BOOKS</value>
      <webElementGuid>1a41b365-2c54-492c-ab20-87691e01cbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOOKS</value>
      <webElementGuid>6cfae65d-a772-41ee-989f-f1833bee50c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/book-app[1]</value>
      <webElementGuid>b33a5166-6230-490b-90e2-ef3b4ec61593</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BOOKS']/parent::*</value>
      <webElementGuid>b5aec591-5efb-48eb-9206-e33b760b774d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//book-app</value>
      <webElementGuid>ab170a2e-0d63-461b-a1aa-d7d5b472da0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//book-app[(text() = 'BOOKS' or . = 'BOOKS')]</value>
      <webElementGuid>5860ea17-6b2c-40c6-896f-07fc8c0399ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
