<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to Cart</name>
   <tag></tag>
   <elementGuidId>c7f72ae7-2b4b-4446-8d77-0f4153e95294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/shop-button/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#content > div.detail > shop-button > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cad65333-5554-42b9-a6c9-21812c0ce3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add this item to cart</value>
      <webElementGuid>440fcb12-b21d-4083-8bc6-7a3eac7e3718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>f6274326-d5b9-46cb-9302-d8f1d8c8f4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;content&quot;]/div[@class=&quot;detail&quot;]/shop-button[1]/button[1]</value>
      <webElementGuid>de09b2f6-3231-47cc-b301-c19c6d0ccfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Mens Tech Shell Full-Zip - SHOP/shop-detail_detail</value>
      <webElementGuid>b5983524-0e02-4392-914e-f3b3912e1f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e4020ec6-ed5c-4f1c-9410-d01fb0c5e2c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/shop-button/button</value>
      <webElementGuid>7e9cfaae-cbfd-48e5-924b-bbe486410926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to Cart']/parent::*</value>
      <webElementGuid>fd73b03f-1a0c-4eb1-8827-28f786285272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add to Cart' or . = 'Add to Cart')]</value>
      <webElementGuid>203773ab-edaa-47b9-b71f-08fdea2b456b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
