<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mens Tech Shell Full-Zip</name>
   <tag></tag>
   <elementGuidId>1e18855a-58fb-448d-bb03-53f0835d0425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Men's Tech Shell Full-Zip']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c89a5794-a756-48a3-9da9-b9ae26732d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>f8d5a9d6-1857-4507-b283-d5481460578b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Men's Tech Shell Full-Zip</value>
      <webElementGuid>80017067-8fa8-4dd8-bdea-e555dd8c3f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;title&quot;]</value>
      <webElementGuid>ab70b17c-a6e4-4457-b693-a1da779fd529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Mens Tech Shell Full-Zip - SHOP/shop-list-item</value>
      <webElementGuid>a9e25f78-f67c-4dc7-9e48-5e19250eee0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02cbea73-2603-4ca5-b78b-54af9e9cbee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Men's Tech Shell Full-Zip']/parent::*</value>
      <webElementGuid>3be10d33-3a1a-4cb3-a1f4-b8012249c863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Men&quot; , &quot;'&quot; , &quot;s Tech Shell Full-Zip&quot;) or . = concat(&quot;Men&quot; , &quot;'&quot; , &quot;s Tech Shell Full-Zip&quot;))]</value>
      <webElementGuid>016a0c23-93d4-4baa-889a-e051bf65885d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
