<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shop-detail_detail</name>
   <tag></tag>
   <elementGuidId>94506072-5053-43bc-9ac1-8be0c3fc0b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//shop-detail[@name = 'detail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iron-pages > shop-detail[name=&quot;detail&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shop-detail</value>
      <webElementGuid>e4ed585f-8db6-4d14-95a3-78f2830539b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detail</value>
      <webElementGuid>a437df2a-f8d9-48da-87ec-c5e414ec1a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iron-selected</value>
      <webElementGuid>d8e3f209-35c1-48fc-b99c-9e861b5a6e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/iron-pages[1]/shop-detail[@class=&quot;iron-selected&quot;]</value>
      <webElementGuid>06e25eec-7186-431e-9c62-79b4e90777e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Mens Tech Shell Full-Zip - SHOP/shop-app_SHOP</value>
      <webElementGuid>0ae83313-e3f7-4ee4-8909-1db6da088f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c7a3f2a-348b-49b6-ba0f-ae47139f8324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//shop-detail[@name = 'detail']</value>
      <webElementGuid>1fcd8828-3d6d-4f4f-b5e3-7282c992cbf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
