<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shop-cart-modal_opened</name>
   <tag></tag>
   <elementGuidId>07cced17-77e7-4080-85bb-8938e7b1ded5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>shop-cart-modal.opened</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shop-cart-modal</value>
      <webElementGuid>7f3b4d3f-7610-4118-8903-1ae47b7e2ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b06e54e5-d392-428c-8436-8708b44cebbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>3c9abc97-61f0-41d7-b0ff-7035383e6635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ab8c44fa-5eb1-44a8-babe-0416e3a7376a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>opened</value>
      <webElementGuid>837bc446-7038-499a-9d15-4c07d6c3626f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/shop-cart-modal[@class=&quot;opened&quot;]</value>
      <webElementGuid>694e7f0d-5ee6-4161-9c9b-04419253500f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Mens Tech Shell Full-Zip - SHOP/shop-app_SHOP</value>
      <webElementGuid>b505abbc-aa2e-4247-8d35-10727856445b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e29d3e07-c4cb-44ff-9e46-45b3e6129546</webElementGuid>
   </webElementProperties>
</WebElementEntity>
