<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shop-app_SHOP</name>
   <tag></tag>
   <elementGuidId>388ab13d-4c3e-4d9e-9ac5-e98f6dbd39c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>shop-app</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='SHOP']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shop-app</value>
      <webElementGuid>a19b6179-f4a5-475b-a9df-4d4b568cf0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>page</name>
      <type>Main</type>
      <value>detail</value>
      <webElementGuid>8e4bf7c6-5aba-4dce-a59f-5363d48120c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHOP</value>
      <webElementGuid>9e4a2d3a-d40a-4f99-bfe4-d1720701c81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/shop-app[1]</value>
      <webElementGuid>3f6e4f79-9e7b-4846-afcc-26b7a853192c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHOP']/parent::*</value>
      <webElementGuid>98aa5416-39ef-42af-b560-50b024f8516e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//shop-app</value>
      <webElementGuid>d638a4c2-02b3-4832-ace8-0305258bfea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//shop-app[(text() = 'SHOP' or . = 'SHOP')]</value>
      <webElementGuid>bc6ab60f-f098-4445-83e9-7e6a81602417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
