<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shop-app_SHOP</name>
   <tag></tag>
   <elementGuidId>dd264a64-7bdb-4c81-891a-f0b11d150e40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>shop-app</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/img[@id=', '&quot;', 'img', '&quot;', ']')])[1]/preceding::shop-app[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shop-app</value>
      <webElementGuid>8fa431b1-8a70-4967-8186-4ee14c8a10b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>page</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>92a2a116-9dae-4e77-bebd-9337709e413e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHOP</value>
      <webElementGuid>9b982047-348e-4216-bd0a-0b47d3ff9d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/shop-app[1]</value>
      <webElementGuid>e26e3be0-7107-4edc-bada-c4f8d29454f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/img[@id=', '&quot;', 'img', '&quot;', ']')])[1]/preceding::shop-app[1]</value>
      <webElementGuid>abac806f-8549-4437-8e54-9b01baed06bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHOP']/parent::*</value>
      <webElementGuid>263f43a8-f006-4722-9a07-cf32a5b7889e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//shop-app</value>
      <webElementGuid>55e38047-41c0-4194-9f94-08a5dee2dd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//shop-app[(text() = 'SHOP' or . = 'SHOP')]</value>
      <webElementGuid>c3658606-1d2e-4cf4-a497-ffb20c1fa154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
