<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_shipAddress</name>
   <tag></tag>
   <elementGuidId>08034839-ad7b-4618-8e28-010bb6af2e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iron-form[@id='checkoutForm']/form/div[2]/section/div[3]/shop-input/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.main-frame > #pages > div.iron-selected > #checkoutForm > form > div.subsection.grid > section > div.row.input-row > shop-input > #shipAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7814735c-ae88-42dd-9599-9141e7fcb18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1182a415-5b32-496c-a2b3-dd49588716d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipAddress</value>
      <webElementGuid>b92ebc41-f548-4ea2-a294-c6fe1143157a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipAddress</value>
      <webElementGuid>ba979ac7-3320-482b-a799-0a84fcc78add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{5,}</value>
      <webElementGuid>2cdc702e-a1a8-4072-9a74-2d65e0ef3af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>631c2f5d-569b-4ff5-8829-f3fca6490f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>shipAddressLabel shipAddressHeading</value>
      <webElementGuid>2218c16e-1ba8-46ed-8ac1-f9c0b2c1a46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;main-frame&quot;]/iron-pages[@id=&quot;pages&quot;]/div[@class=&quot;iron-selected&quot;]/iron-form[@id=&quot;checkoutForm&quot;]/form[1]/div[@class=&quot;subsection grid&quot;]/section[1]/div[@class=&quot;row input-row&quot;]/shop-input[1]/input[@id=&quot;shipAddress&quot;]</value>
      <webElementGuid>1fef588d-f84f-419a-b978-140d0892c52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Checkout - SHOP/shop-checkout_checkout</value>
      <webElementGuid>60ee8d97-0b0d-4a7d-b211-1bf0ca578080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>daaf4e22-838a-4a4f-803d-5384914cf4e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//iron-form[@id='checkoutForm']/form/div[2]/section/div[3]/shop-input/input</value>
      <webElementGuid>bac59f99-89db-46f5-9e3a-7b224d9e788d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'shipAddress' and @name = 'shipAddress' and @placeholder = 'Address']</value>
      <webElementGuid>e9741569-e40a-4891-978d-6958d6284c21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
