<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_shipCity</name>
   <tag></tag>
   <elementGuidId>a461a16d-775b-49ed-9d11-e90319332a29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iron-form[@id='checkoutForm']/form/div[2]/section/div[4]/shop-input/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.main-frame > #pages > div.iron-selected > #checkoutForm > form > div.subsection.grid > section > div.row.input-row > shop-input > #shipCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25d3f0be-386e-4ace-a26c-ce84da19fcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa54983d-1f29-49bc-9c25-662de85baffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipCity</value>
      <webElementGuid>cc6df374-3a22-4871-94cf-c8ef2f245a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipCity</value>
      <webElementGuid>7287ce5d-44f9-422a-8fb0-9448b92ec6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{2,}</value>
      <webElementGuid>7456e4d6-9c29-461b-a316-48933943f887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>0927fddc-2650-406e-9eb1-568632a522d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>shipCityLabel shipAddressHeading</value>
      <webElementGuid>45728ffa-35d1-4df5-a2c7-de5cea3ae334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;main-frame&quot;]/iron-pages[@id=&quot;pages&quot;]/div[@class=&quot;iron-selected&quot;]/iron-form[@id=&quot;checkoutForm&quot;]/form[1]/div[@class=&quot;subsection grid&quot;]/section[1]/div[@class=&quot;row input-row&quot;]/shop-input[1]/input[@id=&quot;shipCity&quot;]</value>
      <webElementGuid>71cf4835-4a72-4ac0-8cc1-84933eeecf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Checkout - SHOP/shop-checkout_checkout</value>
      <webElementGuid>ad774e42-a6db-4782-b310-81e7ab488748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ada21db-e711-4502-b7e4-ca58be2ccbc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//iron-form[@id='checkoutForm']/form/div[2]/section/div[4]/shop-input/input</value>
      <webElementGuid>b83d731b-fe0d-4d68-92e6-b697a34d0e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'shipCity' and @name = 'shipCity' and @placeholder = 'City']</value>
      <webElementGuid>381069d6-93a4-4654-9025-428f5eb80fb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
