<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ccName</name>
   <tag></tag>
   <elementGuidId>17eb91fd-552d-456f-83b7-1ff72a5da0d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iron-form[@id='checkoutForm']/form/div[2]/section[2]/div/shop-input/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.main-frame > #pages > div.iron-selected > #checkoutForm > form > div.subsection.grid > section:nth-of-type(2) > div.row.input-row > shop-input > #ccName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54639ffd-092a-40b8-8aa1-8f7feaad509e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd22fe24-6c0c-4770-9489-a7dbc243af8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ccName</value>
      <webElementGuid>a6757d7e-a9e4-42a6-bd4a-9d3bf5ed00bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ccName</value>
      <webElementGuid>ecf236f9-6142-4f45-9e85-2d8f9549af7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{3,}</value>
      <webElementGuid>333338f7-0826-42f9-be14-a04661d3426c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cardholder Name</value>
      <webElementGuid>08c6fc6e-93cd-4b01-bb64-e6c6cfaf1999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-name</value>
      <webElementGuid>87d53623-4d9b-42fb-a4ac-210e3a903261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;main-frame&quot;]/iron-pages[@id=&quot;pages&quot;]/div[@class=&quot;iron-selected&quot;]/iron-form[@id=&quot;checkoutForm&quot;]/form[1]/div[@class=&quot;subsection grid&quot;]/section[2]/div[@class=&quot;row input-row&quot;]/shop-input[1]/input[@id=&quot;ccName&quot;]</value>
      <webElementGuid>b767df88-cfcf-44b2-b9ac-58caec7b1f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Checkout - SHOP/shop-checkout_checkout</value>
      <webElementGuid>4f6f9d7c-ddd8-48b9-b599-07810afa7927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f6ce193-8564-4af0-9595-ceed7ab24308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//iron-form[@id='checkoutForm']/form/div[2]/section[2]/div/shop-input/input</value>
      <webElementGuid>0d915b9a-6310-4358-b6d3-a4e3f5706ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ccName' and @name = 'ccName' and @placeholder = 'Cardholder Name']</value>
      <webElementGuid>59578991-2a69-44b5-b380-5f5984bd1243</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
