<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_accountPhone</name>
   <tag></tag>
   <elementGuidId>968769e2-40df-4578-8569-69748dcd799e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iron-form[@id='checkoutForm']/form/div[2]/section/div[2]/shop-input/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.main-frame > #pages > div.iron-selected > #checkoutForm > form > div.subsection.grid > section > div.row.input-row > shop-input > #accountPhone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33859c9d-c23d-425f-a767-fba51b8e7e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>68305857-ff6c-4133-b4ca-9d7b9b622c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountPhone</value>
      <webElementGuid>0c816886-2966-45a6-b7bb-78125849a5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountPhone</value>
      <webElementGuid>d58541b9-d8cd-4a49-ade8-37f2143600c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d{10,}</value>
      <webElementGuid>e51a937a-4094-494f-8a21-d4ceb834e9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>ee316549-51fc-471f-8b7c-dcc775d6d794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>accountPhoneLabel accountInfoHeading</value>
      <webElementGuid>f89fb545-5886-4c9b-be26-eb2a46d66ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;main-frame&quot;]/iron-pages[@id=&quot;pages&quot;]/div[@class=&quot;iron-selected&quot;]/iron-form[@id=&quot;checkoutForm&quot;]/form[1]/div[@class=&quot;subsection grid&quot;]/section[1]/div[@class=&quot;row input-row&quot;]/shop-input[1]/input[@id=&quot;accountPhone&quot;]</value>
      <webElementGuid>4f2eb3e2-93c3-4ab9-ae93-00e4d17b85da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Checkout - SHOP/shop-checkout_checkout</value>
      <webElementGuid>8c425631-988c-41d5-8938-802996715dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>983cbb28-4e94-48c5-9cbf-f5207c9803b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//iron-form[@id='checkoutForm']/form/div[2]/section/div[2]/shop-input/input</value>
      <webElementGuid>8ca9b77f-267c-4c0a-9c1f-485285aba6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'accountPhone' and @name = 'accountPhone' and @placeholder = 'Phone Number']</value>
      <webElementGuid>868fe05a-6ee0-4c7e-b780-cdb5d6968d12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
