<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_shipState</name>
   <tag></tag>
   <elementGuidId>7640aa0d-9cda-4743-93ed-9e3255f34c9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iron-form[@id='checkoutForm']/form/div[2]/section/div[5]/shop-input/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.main-frame > #pages > div.iron-selected > #checkoutForm > form > div.subsection.grid > section > div.row.input-row > shop-input > #shipState</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>103c843e-d0d7-4658-b7be-48ca74ea9a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d440ccab-4753-4bfa-8e62-cbdf17106e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipState</value>
      <webElementGuid>6be4607f-09d1-4e76-9bd3-694bd746cf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipState</value>
      <webElementGuid>c5543313-2ced-470f-b99d-76ad56615ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{2,}</value>
      <webElementGuid>8835618e-4bfa-4673-9957-158a61bca2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>State/Province</value>
      <webElementGuid>26dc34b0-b968-477b-8384-2d6ac33164e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>shipStateLabel shipAddressHeading</value>
      <webElementGuid>204c7c9e-2726-4956-8d12-4f307d587746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;main-frame&quot;]/iron-pages[@id=&quot;pages&quot;]/div[@class=&quot;iron-selected&quot;]/iron-form[@id=&quot;checkoutForm&quot;]/form[1]/div[@class=&quot;subsection grid&quot;]/section[1]/div[@class=&quot;row input-row&quot;]/shop-input[1]/input[@id=&quot;shipState&quot;]</value>
      <webElementGuid>c6c8ff36-0bc3-41cd-9a86-7b9291680eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Checkout - SHOP/shop-checkout_checkout</value>
      <webElementGuid>13c1c950-443f-4bf3-91a2-1445c04eeda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb0a9839-8fa5-4d20-bb0f-8ae84847ed73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//iron-form[@id='checkoutForm']/form/div[2]/section/div[5]/shop-input/input</value>
      <webElementGuid>d54d9d8b-843e-4fd2-8a3b-161f992eaed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'shipState' and @name = 'shipState' and @placeholder = 'State/Province']</value>
      <webElementGuid>b67a6254-e371-4ad2-99d3-3be4c72fc9a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
