<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shop-app_SHOP</name>
   <tag></tag>
   <elementGuidId>6d0539f6-0024-4a05-b30b-847e2b7c5f8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='SHOP']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>shop-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shop-app</value>
      <webElementGuid>c79beaa8-3508-459c-9ca8-29dd2bb7de24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>page</name>
      <type>Main</type>
      <value>checkout</value>
      <webElementGuid>2d4194cf-67ec-417a-afff-d554ecf36e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHOP</value>
      <webElementGuid>34b2e006-8081-495d-9be4-7a6c12ce4022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/shop-app[1]</value>
      <webElementGuid>da741775-5525-41c4-8979-883360ae98fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHOP']/parent::*</value>
      <webElementGuid>7db1b014-250e-47a6-a836-4d2d023ed4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//shop-app</value>
      <webElementGuid>e6f6d478-9951-437a-80fd-c7561f40df20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//shop-app[(text() = 'SHOP' or . = 'SHOP')]</value>
      <webElementGuid>c5d41fe2-b593-4c66-a766-08b357b2bf11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
