<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shop-list-item</name>
   <tag></tag>
   <elementGuidId>6e159f5d-e6c4-4d80-86a1-e6b23179eaf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.grid > li > a > shop-list-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shop-list-item</value>
      <webElementGuid>967b2b34-fdb1-4e71-b883-9d06960825aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/ul[@class=&quot;grid&quot;]/li[1]/a[1]/shop-list-item[1]</value>
      <webElementGuid>6a4c04f5-1c9c-47fd-9674-8083953eab5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR Shop-polymer/Page_Mens T-Shirts - SHOP/shop-list_list</value>
      <webElementGuid>f32383f9-f999-4332-bfd7-b9f2d0999879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8dafb7ee-c4db-4d0b-bca8-3d43a323ada8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
